// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnqsdwqmdhgarwlhsijf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucXNkd3FtZGhnYXJ3bGhzaWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzQ3MTUsImV4cCI6MjA2ODE1MDcxNX0.ZcKPknUgvsW1eg5HQMb2veJGBw_YwT5BYHB532_HYvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});